server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: ${CONFIG_SERVER_NAME:config-server}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jandresmartinez/cloud-config.git
          basedir: ${CONFIG_SERVER_CHECKOUT_FOLDER:../configurations}
          searchPaths: 'configurations'


